insightsengineering/rbmi

- tests/testthat/helper-misc.R
- tests/testthat/test-fullusage.R
Partially covers #115 
I haven't covered the case of only 1 arm. 
This PR did raise an interesting question for me though which is should we always be adding ivars$group into the MMRM model. Surely its plausible that the variable we create our reference groups by isn't actually a prognostic covariate in the model ?
> Test multiarm

- man/rubin_df.Rd
- man/rubin_rules.Rd
@gowerc Sorry, I had problem in running `devtools::document()` as discussed. I have now updated the Rd files of the functions I wrote the documentation before.
> modify Rd files

- R/draws.R
- R/methods.R
- man/method.Rd
- tests/testthat/_snaps/print.md
- tests/testthat/test-methods.R
@nociale , added some initial doc files for the methods objects. Please let me know what you think
> added methods docs

- R/methods.R
- man/method.Rd
> added remark on stan seed

- R/pool.R
- R/simulate.R
- tests/testthat/test-expand.R
- tests/testthat/test-pool.R
- tests/testthat/test-simulate.R
> added tests for areas with no coverage

- R/draws.R
- tests/testthat/test-draws.R
Addresses #157.  So the functionality was already in place but the user would have had to set data_ice to NULL manually. In this PR I just set data_ice to NULL by default. I also added some unit tests to prove that it sets is_mar to TRUE for everyone by default and is_post_ice to FALSE for everyone by default.
> added default values and unit tests for data_ice

- R/analyse.R
Small changes to the docu only.
> Changes to analyse docu

- tests/testthat/test-draws.R
> removed commented code

- R/pool.R
Please also re-check that one- and two-sided p-values are correct for both percentile and normal/t-distribution based methods.
> Update pool docu

- R/draws.R
- man/as_mmrm_df.Rd
- man/draws.Rd
- man/fit_mmrm.Rd
- man/fit_mmrm_multiopt.Rd
- man/get_mmrm_sample.Rd
- man/random_effects_expr.Rd
Simply run `devtools::document()` to update Rd files
> update Rd files

- R/lsmeans.R
- man/lsmeans.Rd
> modify emmeans url

- R/pool.R
- tests/testthat/test-pool.R
> pool when n_samples = 0,1

- DESCRIPTION
- vignettes/references.bib
- vignettes/stat_specs.Rmd
Vignette related to statistical specifications of the package
> vignette stats specs

- DESCRIPTION
- R/expand.R
- tests/testthat/test-expand.R
- tests/testthat/test-print.R
closes #240 
@nociale  FYI this is the patch to fix the identified locf issue. ~~Please **don't** merge until we get clarity on how to handle this with Mango~~
> added additional unit tests to catch locf bug

- vignettes/quickstart.Rmd
Closes #216 
Just added all the code at the end of the quickstart vignette
> add code at the end of quickstart vignette

- R/longData.R
- tests/testthat/helper-misc.R
- tests/testthat/test-longData.R
> unique warning when passing from non-MAR to MAR

- vignettes/quickstart.Rmd
Only print head of imputed datatasets in quickstart vignette
> only head of imputed datasets

- R/analyse.R
- data-raw/create_print_test_data.R
- tests/testthat/_snaps/print.md
- tests/testthat/test-print.R
> updated analysis print method to contain function name

- R/draws.R
- R/methods.R
- tests/testthat/_snaps/print.md
> removed redundant nsamples from print method

- tests/testthat/test-parallel.R
> updated parallel run time

- R/ancova.R
- man/ancova.Rd
- vignettes/quickstart.Rmd
> specify ref correspond to first level of group variable

- R/draws.R
- man/draws.Rd
- misc/joss_manuscript/references.bib
- vignettes/references.bib
Hi @gowerc 
I have changed the title of the newly updated conditional mean imputation manuscript on arxiv (apologies, but having twice "impute" in the title seemed too ugly) and adapted the reference of draws and the bib-files (vignettes and JOSS paper) accordingly. I also corrected another typo in the bib files.
> Bib changes

- R/delta.R
- tests/testthat/test-delta.R
> fixed incorrect factor leveling

- R/longData.R
- tests/testthat/test-longData.R
> Resolved issue of error message giving wrong visit

- R/longData.R
- tests/testthat/test-longData.R
> reworked get_data() code

- R/simulate_data.R
- man/simulate_data.Rd
- tests/testthat/test-simulate_data.R
> change error message prob_ice2 and update documentation

- .github/workflows/validate_generic_master.yaml
By using the new version of theValidatoR
> Fix validation workflow

- misc/joss_manuscript/paper.md
> Minor fixes to JOSS paper

- DESCRIPTION
- NEWS.md
- tests/testthat/test-mmrm.R
Update to fix comments from internal validation team. Needed to remove native pipes in order for testing code to work on legacy servers.
> updated news / description
